version: 2

build:
    os: ubuntu-22.04
    tools:
        python: '3.11'
    jobs:
      pre_build:
        - python3 icebox/icebox_html.py  -3 -d docs/source/_static/bitdocs-384

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/source/requirements.txt
